name: setoran_mobil
description: Aplikasi manajemen setoran dan perbaikan kendaraan
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Database Lokal
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Format Tanggal & Rupiah
  intl: ^0.19.0

  # Chart Dashboard
  fl_chart: ^0.68.0

  # Export & Backup
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  excel: ^4.0.6

  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
